In [1]:
import glob
import pybrain
from pybrain.structure import FeedForwardNetwork
from pybrain.structure import LinearLayer, SigmoidLayer
from pybrain.structure import FullConnection
from pybrain.datasets import SupervisedDataSet
from pybrain.supervised.trainers import BackpropTrainer
import matplotlib.pyplot as plt
import datetime
%matplotlib inline
import random
import ast
import time
import sqlalchemy
from sqlalchemy import *
from sqlalchemy import event
import sqlite3
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import *
import urllib2
import urllib
import json
import glob
import pprint
import dateutil.parser
import pprint
import re
from sklearn import linear_model, datasets
import time
from sklearn.naive_bayes import GaussianNB
import nltk
from collections import defaultdict
from sklearn import svm
pp = pprint.PrettyPrinter(indent=4)
import numpy
import time
import sqlalchemy
from sqlalchemy import *
from sqlalchemy import event
from sqlalchemy.dialects.mysql import LONGTEXT
import sqlite3
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import *
import urllib2
import urllib
import json
import pprint
import dateutil.parser
import gevent
import datetime
import marshal

import re, math, collections, itertools
import nltk, nltk.classify.util, nltk.metrics
from nltk.classify import NaiveBayesClassifier
from nltk.metrics import BigramAssocMeasures
from nltk.probability import FreqDist, ConditionalFreqDist
import numpy as np
import csv
import re
import nltk.classify.util
from nltk.classify import NaiveBayesClassifier
from nltk.corpus import movie_reviews
from sklearn.svm import LinearSVC
from nltk.classify.scikitlearn import SklearnClassifier
import os

In [21]:
import csv
from os.path import expanduser
home = expanduser("~")
with open(home + "/forex/data/datasets/WorldDevelopmentIndex/WDI_Data.csv", "r") as csvfile:
    with open(home + "/forex/data/datasets/WorldDevelopmentIndex/WDI_Data_out_20.csv", "w") as outfile:
        reader = csv.DictReader(csvfile)
        writer = csv.writer(outfile)
        writer.writerow(["Country Name", "Country Code", "Indicator Code", "Year", "Value"])
        for line in reader:
            for key in line.keys():
                if '20' in key:
                    if not line[key] == "":
                        writer.writerow([line['Country Name'], line['Country Code'], line['Indicator Code'], key, line[key]])

In [20]:
with open(home + "/forex/data/datasets/WorldDevelopmentIndex/WDI_Data_out.csv", "r") as outfile:
    print outfile.readline()
    print outfile.readline()
    print outfile.readline()
    print outfile.readline()
    print outfile.readline()
    print outfile.readline()

Country Name,Country Code,Indicator Code,Year,Value

Afghanistan,AFG,EG.ELC.RNEW.ZS,1997,7.23880597014925E+01

Afghanistan,AFG,EG.ELC.RNEW.ZS,1996,7.03703703703704E+01

Afghanistan,AFG,EG.ELC.RNEW.ZS,1991,6.79802955665025E+01

Afghanistan,AFG,EG.ELC.RNEW.ZS,1990,6.77304964539007E+01

Afghanistan,AFG,EG.ELC.RNEW.ZS,1993,6.83453237410072E+01

In [7]:
out[1]

{'1960': '',
 '1961': '',
 '1962': '',
 '1963': '',
 '1964': '',
 '1965': '',
 '1966': '',
 '1967': '',
 '1968': '',
 '1969': '',
 '1970': '',
 '1971': '',
 '1972': '',
 '1973': '',
 '1974': '',
 '1975': '',
 '1976': '',
 '1977': '',
 '1978': '',
 '1979': '',
 '1980': '',
 '1981': '',
 '1982': '',
 '1983': '',
 '1984': '',
 '1985': '',
 '1986': '',
 '1987': '',
 '1988': '',
 '1989': '',
 '1990': '6.77304964539007E+01',
 '1991': '6.79802955665025E+01',
 '1992': '6.79943100995733E+01',
 '1993': '6.83453237410072E+01',
 '1994': '6.87045123726346E+01',
 '1995': '6.90370370370370E+01',
 '1996': '7.03703703703704E+01',
 '1997': '7.23880597014925E+01',
 '1998': '7.44360902255639E+01',
 '1999': '7.37226277372263E+01',
 '2000': '7.49890940817217E+01',
 '2001': '7.28114599913182E+01',
 '2002': '7.90639711991138E+01',
 '2003': '6.62909836065574E+01',
 '2004': '7.24358974358974E+01',
 '2005': '7.40618101545254E+01',
 '2006': '7.07557502738226E+01',
 '2007': '7.20000000000000E+01',
 '2008': '6.86548223350254E+01',
 '2009': '8.71766029246344E+01',
 '2010': '8.59865470852018E+01',
 '2011': '8.24875621890547E+01',
 '2012': '0.00000000000000E+00',
 '2013': '',
 '2014': '',
 'Country Code': 'AFG',
 'Country Name': 'Afghanistan',
 'Indicator Code': 'EG.ELC.RNEW.ZS',
 'Indicator Name': 'Renewable electricity output (% of total electricity output)'}

In [ ]:
i want to extract all the features of all the countries for a certain year, and use that to predict the next year's retail sales.

there's 300000 features
limit it to only features that have good data for most countries back 15+ years

put the data into a format with each row containing country, indicator type, year, and data value

In [26]:
months = {"Jan.": 1, "Feb.": 2, "Mar.": 3, "Apr.": 4, "May": 5, "Jun.": 6, "Jul.": 7, "Aug.": 8, "Sep.": 9, "Oct.": 10, "Nov.": 11, "Dec.": 12}

In [33]:
import csv
from os.path import expanduser
home = expanduser("~")
with open(home + "/forex/data/datasets/monthly_retail_sales/all.csv", "r") as csvfile:
    with open(home + "/forex/data/datasets/monthly_retail_sales/all_out.csv", "w") as outfile:
        reader = csv.DictReader(csvfile)
        writer = csv.writer(outfile, quoting=csv.QUOTE_ALL)
        #writer.writerow(["NAICS", "Type", "Year", "Month", "Value"])
        for line in reader:
            for key in line.keys():
                if key != "Type" and key != "NAICS":
                    if line[key] != "" and line[key] != "(S)" and line[key] != "(NA)":
                        month, year = key.split(" ")
                        writer.writerow([line['NAICS'], line['Type'].replace(",", ""), year, months[month], line[key].replace(",", "")])

In [24]:
import csv
from os.path import expanduser
home = expanduser("~")
with open(home + "/forex/data/datasets/monthly_retail_sales/all.csv", "r") as csvfile:
    with open(home + "/forex/data/datasets/monthly_retail_sales/all_out.csv", "w") as outfile:
        reader = csv.DictReader(csvfile)
        out = []
        for row in reader:
            out.append(row)

In [25]:
out[1]

{'Apr. 1992': '127,587',
 'Apr. 1993': '135,401',
 'Apr. 1994': '141,977',
 'Apr. 1995': '148,170',
 'Apr. 1996': '157,622',
 'Apr. 1997': '164,024',
 'Apr. 1998': '174,475',
 'Apr. 1999': '185,914',
 'Apr. 2000': '198,431',
 'Apr. 2001': '207,647',
 'Apr. 2002': '213,955',
 'Apr. 2003': '221,855',
 'Apr. 2004': '241,939',
 'Apr. 2005': '257,963',
 'Apr. 2006': '275,487',
 'Apr. 2007': '281,270',
 'Apr. 2008': '295,217',
 'Apr. 2009': '274,057',
 'Apr. 2010': '292,215',
 'Apr. 2011': '311,384',
 'Apr. 2012': '319,594',
 'Apr. 2013': '327,859',
 'Apr. 2014': '342,380',
 'Apr. 2015(p)': '342,409',
 'Aug. 1992': '134,928',
 'Aug. 1993': '141,612',
 'Aug. 1994': '154,061',
 'Aug. 1995': '160,769',
 'Aug. 1996': '170,581',
 'Aug. 1997': '177,182',
 'Aug. 1998': '182,720',
 'Aug. 1999': '195,625',
 'Aug. 2000': '212,094',
 'Aug. 2001': '221,436',
 'Aug. 2002': '227,673',
 'Aug. 2003': '239,394',
 'Aug. 2004': '249,940',
 'Aug. 2005': '274,481',
 'Aug. 2006': '292,798',
 'Aug. 2007': '303,383',
 'Aug. 2008': '313,261',
 'Aug. 2009': '287,366',
 'Aug. 2010': '296,801',
 'Aug. 2011': '323,407',
 'Aug. 2012': '337,412',
 'Aug. 2013': '347,115',
 'Aug. 2014': '356,572',
 'Dec. 1992': '175,771',
 'Dec. 1993': '185,536',
 'Dec. 1994': '198,627',
 'Dec. 1995': '203,689',
 'Dec. 1996': '211,843',
 'Dec. 1997': '220,677',
 'Dec. 1998': '234,123',
 'Dec. 1999': '257,441',
 'Dec. 2000': '263,717',
 'Dec. 2001': '265,205',
 'Dec. 2002': '273,540',
 'Dec. 2003': '290,828',
 'Dec. 2004': '314,679',
 'Dec. 2005': '334,946',
 'Dec. 2006': '346,996',
 'Dec. 2007': '357,006',
 'Dec. 2008': '332,086',
 'Dec. 2009': '344,705',
 'Dec. 2010': '362,425',
 'Dec. 2011': '380,986',
 'Dec. 2012': '388,516',
 'Dec. 2013': '398,511',
 'Dec. 2014': '412,103',
 'Feb. 1992': '115,862',
 'Feb. 1993': '117,300',
 'Feb. 1994': '123,634',
 'Feb. 1995': '130,679',
 'Feb. 1996': '142,805',
 'Feb. 1997': '147,430',
 'Feb. 1998': '153,119',
 'Feb. 1999': '163,598',
 'Feb. 2000': '183,688',
 'Feb. 2001': '186,254',
 'Feb. 2002': '190,149',
 'Feb. 2003': '198,030',
 'Feb. 2004': '217,214',
 'Feb. 2005': '228,117',
 'Feb. 2006': '246,599',
 'Feb. 2007': '253,789',
 'Feb. 2008': '274,940',
 'Feb. 2009': '249,611',
 'Feb. 2010': '259,358',
 'Feb. 2011': '274,963',
 'Feb. 2012': '302,230',
 'Feb. 2013': '301,828',
 'Feb. 2014': '304,556',
 'Feb. 2015': '305,303',
 'Jan. 1992': '116,565',
 'Jan. 1993': '121,021',
 'Jan. 1994': '124,850',
 'Jan. 1995': '134,789',
 'Jan. 1996': '140,160',
 'Jan. 1997': '151,994',
 'Jan. 1998': '158,132',
 'Jan. 1999': '165,591',
 'Jan. 2000': '177,649',
 'Jan. 2001': '191,485',
 'Jan. 2002': '195,033',
 'Jan. 2003': '206,194',
 'Jan. 2004': '220,314',
 'Jan. 2005': '231,325',
 'Jan. 2006': '252,809',
 'Jan. 2007': '262,292',
 'Jan. 2008': '276,893',
 'Jan. 2009': '260,307',
 'Jan. 2010': '264,982',
 'Jan. 2011': '277,963',
 'Jan. 2012': '293,066',
 'Jan. 2013': '307,106',
 'Jan. 2014': '312,448',
 'Jan. 2015': '317,033',
 'Jul. 1992': '132,076',
 'Jul. 1993': '140,704',
 'Jul. 1994': '147,625',
 'Jul. 1995': '153,443',
 'Jul. 1996': '163,040',
 'Jul. 1997': '173,049',
 'Jul. 1998': '181,661',
 'Jul. 1999': '193,716',
 'Jul. 2000': '203,886',
 'Jul. 2001': '210,053',
 'Jul. 2002': '219,025',
 'Jul. 2003': '231,445',
 'Jul. 2004': '249,163',
 'Jul. 2005': '264,117',
 'Jul. 2006': '281,314',
 'Jul. 2007': '293,257',
 'Jul. 2008': '314,099',
 'Jul. 2009': '285,925',
 'Jul. 2010': '295,178',
 'Jul. 2011': '315,611',
 'Jul. 2012': '320,983',
 'Jul. 2013': '337,195',
 'Jul. 2014': '350,695',
 'Jun. 1992': '130,274',
 'Jun. 1993': '138,540',
 'Jun. 1994': '148,644',
 'Jun. 1995': '156,922',
 'Jun. 1996': '162,597',
 'Jun. 1997': '169,901',
 'Jun. 1998': '179,213',
 'Jun. 1999': '191,552',
 'Jun. 2000': '208,286',
 'Jun. 2001': '215,142',
 'Jun. 2002': '217,787',
 'Jun. 2003': '226,376',
 'Jun. 2004': '245,689',
 'Jun. 2005': '265,567',
 'Jun. 2006': '286,016',
 'Jun. 2007': '296,815',
 'Jun. 2008': '309,122',
 'Jun. 2009': '285,029',
 'Jun. 2010': '294,164',
 'Jun. 2011': '318,644',
 'Jun. 2012': '325,199',
 'Jun. 2013': '333,053',
 'Jun. 2014': '345,578',
 'Mar. 1992': '124,200',
 'Mar. 1993': '131,181',
 'Mar. 1994': '143,525',
 'Mar. 1995': '149,748',
 'Mar. 1996': '156,474',
 'Mar. 1997': '167,468',
 'Mar. 1998': '170,482',
 'Mar. 1999': '185,818',
 'Mar. 2000': '204,448',
 'Mar. 2001': '209,049',
 'Mar. 2002': '215,490',
 'Mar. 2003': '221,829',
 'Mar. 2004': '240,415',
 'Mar. 2005': '258,532',
 'Mar. 2006': '279,239',
 'Mar. 2007': '290,309',
 'Mar. 2008': '296,336',
 'Mar. 2009': '271,553',
 'Mar. 2010': '293,490',
 'Mar. 2011': '312,098',
 'Mar. 2012': '333,112',
 'Mar. 2013': '339,089',
 'Mar. 2014': '341,407',
 'Mar. 2015': '345,218',
 'May 1992': '133,608',
 'May 1994': '147,862',
 'May 1995': '157,703',
 'May 1996': '168,786',
 'May 1998': '176,251',
 'May 1999': '194,291',
 'May 2000': '210,656',
 'May 2001': '221,671',
 'May 2002': '228,248',
 'May 2003': '235,659',
 'May 2004': '250,917',
 'May 2005': '267,021',
 'May 2006': '292,043',
 'May 2007': '306,329',
 'May 2008': '321,854',
 'May 2009': '290,148',
 'May 2010': '300,631',
 'May 2011': '322,866',
 'May 2012': '338,945',
 'May 2013': '351,268',
 'May 2014': '364,347',
 'NAICS': '1',
 'Nov. 1992': '139,187',
 'Nov. 1993': '148,461',
 'Nov. 1994': '158,908',
 'Nov. 1995': '166,150',
 'Nov. 1996': '175,816',
 'Nov. 1997': '179,711',
 'Nov. 1998': '188,435',
 'Nov. 1999': '204,250',
 'Nov. 2000': '218,058',
 'Nov. 2001': '222,341',
 'Nov. 2002': '230,116',
 'Nov. 2003': '239,588',
 'Nov. 2004': '259,038',
 'Nov. 2005': '278,953',
 'Nov. 2006': '289,416',
 'Nov. 2007': '310,458',
 'Nov. 2008': '287,843',
 'Nov. 2009': '289,552',
 'Nov. 2010': '307,229',
 'Nov. 2011': '327,363',
 'Nov. 2012': '341,874',
 'Nov. 2013': '348,252',
 'Nov. 2014': '357,040',
 'Oct. 1992': '136,917',
 'Oct. 1993': '142,450',
 'Oct. 1994': '151,778',
 'Oct. 1995': '155,556',
 'Oct. 1996': '168,434',
 'Oct. 1997': '176,680',
 'Oct. 1998': '184,751',
 'Oct. 1999': '195,657',
 'Oct. 2000': '207,094',
 'Oct. 2001': '212,062',
 'Oct. 2002': '221,211',
 'Oct. 2003': '235,903',
 'Oct. 2004': '250,981',
 'Oct. 2005': '272,540',
 'Oct. 2006': '278,431',
 'Oct. 2007': '294,220',
 'Oct. 2008': '294,982',
 'Oct. 2009': '283,936',
 'Oct. 2010': '294,084',
 'Oct. 2011': '313,717',
 'Oct. 2012': '327,545',
 'Oct. 2013': '337,258',
 'Oct. 2014': '351,578',
 'Sep. 1992': '128,734',
 'Sep. 1993': '137,132',
 'Sep. 1994': '147,603',
 'Sep. 1995': '153,295',
 'Sep. 1996': '158,129',
 'Sep. 1997': '167,947',
 'Sep. 1998': '174,613',
 'Sep. 1999': '189,333',
 'Sep. 2000': '203,320',
 'Sep. 2001': '200,982',
 'Sep. 2002': '208,039',
 'Sep. 2003': '223,768',
 'Sep. 2004': '239,944',
 'Sep. 2005': '263,877',
 'Sep. 2006': '273,214',
 'Sep. 2007': '280,466',
 'Sep. 2008': '290,164',
 'Sep. 2009': '272,718',
 'Sep. 2010': '284,615',
 'Sep. 2011': '308,198',
 'Sep. 2012': '314,665',
 'Sep. 2013': '321,225',
 'Sep. 2014': '335,829',
 'Type': 'Retail sales and food services excl motor vehicle and parts'}